# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_producto.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_producto(object):
    def setupUi(self, form_producto):
        form_producto.setObjectName("form_producto")
        form_producto.resize(712, 577)
        form_producto.setStyleSheet("background-color: rgb(140, 198, 63);")
        self.label_6 = QtWidgets.QLabel(form_producto)
        self.label_6.setGeometry(QtCore.QRect(40, 270, 171, 17))
        self.label_6.setObjectName("label_6")
        self.btn_guardar = QtWidgets.QPushButton(form_producto)
        self.btn_guardar.setGeometry(QtCore.QRect(510, 520, 89, 25))
        self.btn_guardar.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_guardar.setObjectName("btn_guardar")
        self.label = QtWidgets.QLabel(form_producto)
        self.label.setGeometry(QtCore.QRect(70, 150, 81, 17))
        self.label.setObjectName("label")
        self.cbx_categoria = QtWidgets.QComboBox(form_producto)
        self.cbx_categoria.setGeometry(QtCore.QRect(160, 150, 181, 25))
        self.cbx_categoria.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.cbx_categoria.setObjectName("cbx_categoria")
        self.cbx_categoria.addItem("")
        self.cbx_categoria.addItem("")
        self.cbx_categoria.addItem("")
        self.btn_limpiar = QtWidgets.QPushButton(form_producto)
        self.btn_limpiar.setGeometry(QtCore.QRect(600, 520, 89, 25))
        self.btn_limpiar.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_limpiar.setObjectName("btn_limpiar")
        self.label_10 = QtWidgets.QLabel(form_producto)
        self.label_10.setGeometry(QtCore.QRect(440, 150, 41, 25))
        self.label_10.setObjectName("label_10")
        self.lne_lote = QtWidgets.QLineEdit(form_producto)
        self.lne_lote.setGeometry(QtCore.QRect(492, 150, 181, 25))
        self.lne_lote.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lne_lote.setText("")
        self.lne_lote.setObjectName("lne_lote")
        self.lb_id_codigo = QtWidgets.QLabel(form_producto)
        self.lb_id_codigo.setGeometry(QtCore.QRect(30, 540, 67, 17))
        self.lb_id_codigo.setObjectName("lb_id_codigo")
        self.label_2 = QtWidgets.QLabel(form_producto)
        self.label_2.setGeometry(QtCore.QRect(90, 190, 61, 17))
        self.label_2.setObjectName("label_2")
        self.cbx_unidad = QtWidgets.QComboBox(form_producto)
        self.cbx_unidad.setGeometry(QtCore.QRect(160, 190, 171, 25))
        self.cbx_unidad.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.cbx_unidad.setObjectName("cbx_unidad")
        self.cbx_unidad.addItem("")
        self.cbx_unidad.addItem("")
        self.cbx_unidad.addItem("")
        self.text_info = QtWidgets.QPlainTextEdit(form_producto)
        self.text_info.setGeometry(QtCore.QRect(50, 310, 611, 201))
        self.text_info.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.text_info.setObjectName("text_info")
        self.layoutWidget = QtWidgets.QWidget(form_producto)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 40, 651, 95))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.lne_nombre = QtWidgets.QLineEdit(self.layoutWidget)
        self.lne_nombre.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lne_nombre.setObjectName("lne_nombre")
        self.gridLayout.addWidget(self.lne_nombre, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.lne_descripcion = QtWidgets.QLineEdit(self.layoutWidget)
        self.lne_descripcion.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lne_descripcion.setText("")
        self.lne_descripcion.setObjectName("lne_descripcion")
        self.gridLayout.addWidget(self.lne_descripcion, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lne_codigo_interno = QtWidgets.QLineEdit(self.layoutWidget)
        self.lne_codigo_interno.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lne_codigo_interno.setText("")
        self.lne_codigo_interno.setObjectName("lne_codigo_interno")
        self.gridLayout.addWidget(self.lne_codigo_interno, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 2, 1, 1)
        self.dte_fec = QtWidgets.QDateEdit(self.layoutWidget)
        self.dte_fec.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.dte_fec.setObjectName("dte_fec")
        self.gridLayout.addWidget(self.dte_fec, 1, 3, 2, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 2, 1)
        self.lne_codigo_producto = QtWidgets.QLineEdit(self.layoutWidget)
        self.lne_codigo_producto.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lne_codigo_producto.setText("")
        self.lne_codigo_producto.setObjectName("lne_codigo_producto")
        self.gridLayout.addWidget(self.lne_codigo_producto, 2, 1, 2, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.lne_marca = QtWidgets.QLineEdit(self.layoutWidget)
        self.lne_marca.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lne_marca.setText("")
        self.lne_marca.setObjectName("lne_marca")
        self.gridLayout.addWidget(self.lne_marca, 3, 3, 1, 1)

        self.retranslateUi(form_producto)
        QtCore.QMetaObject.connectSlotsByName(form_producto)

    def retranslateUi(self, form_producto):
        _translate = QtCore.QCoreApplication.translate
        form_producto.setWindowTitle(_translate("form_producto", "Formulario de Producto"))
        self.label_6.setText(_translate("form_producto", "Informacion adicional : "))
        self.btn_guardar.setText(_translate("form_producto", "Guardar"))
        self.label.setText(_translate("form_producto", "Categoria :"))
        self.cbx_categoria.setItemText(0, _translate("form_producto", "Libreria"))
        self.cbx_categoria.setItemText(1, _translate("form_producto", "Almacen"))
        self.cbx_categoria.setItemText(2, _translate("form_producto", "Autopartes"))
        self.btn_limpiar.setText(_translate("form_producto", "Limpiar"))
        self.label_10.setText(_translate("form_producto", "Lote : "))
        self.lb_id_codigo.setText(_translate("form_producto", "__"))
        self.label_2.setText(_translate("form_producto", "Unidad : "))
        self.cbx_unidad.setItemText(0, _translate("form_producto", "Kg"))
        self.cbx_unidad.setItemText(1, _translate("form_producto", "Unidad"))
        self.cbx_unidad.setItemText(2, _translate("form_producto", "Litro"))
        self.label_3.setText(_translate("form_producto", "Nombre : "))
        self.label_5.setText(_translate("form_producto", "Descripcion :"))
        self.label_4.setText(_translate("form_producto", "Codigo interno:"))
        self.label_9.setText(_translate("form_producto", "Fecha vencimiento :"))
        self.label_7.setText(_translate("form_producto", "Codigo producto:"))
        self.label_8.setText(_translate("form_producto", "Marca:"))

