# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_entrada.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_entrada(object):
    def setupUi(self, form_entrada):
        form_entrada.setObjectName("form_entrada")
        form_entrada.resize(864, 500)
        form_entrada.setStyleSheet("background-color: rgb(140, 198, 63);")
        self.btn_buscar = QtWidgets.QPushButton(form_entrada)
        self.btn_buscar.setGeometry(QtCore.QRect(750, 30, 89, 25))
        self.btn_buscar.setObjectName("btn_buscar")
        self.lne_nombre_buscar = QtWidgets.QLineEdit(form_entrada)
        self.lne_nombre_buscar.setGeometry(QtCore.QRect(170, 30, 231, 25))
        self.lne_nombre_buscar.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lne_nombre_buscar.setObjectName("lne_nombre_buscar")
        self.btn_agregar = QtWidgets.QPushButton(form_entrada)
        self.btn_agregar.setGeometry(QtCore.QRect(750, 120, 89, 25))
        self.btn_agregar.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_agregar.setObjectName("btn_agregar")
        self.label = QtWidgets.QLabel(form_entrada)
        self.label.setGeometry(QtCore.QRect(20, 30, 141, 17))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(form_entrada)
        self.line.setGeometry(QtCore.QRect(20, 100, 821, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(form_entrada)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 141, 17))
        self.label_2.setObjectName("label_2")
        self.lne_codigo_buscar = QtWidgets.QLineEdit(form_entrada)
        self.lne_codigo_buscar.setGeometry(QtCore.QRect(170, 60, 231, 25))
        self.lne_codigo_buscar.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lne_codigo_buscar.setObjectName("lne_codigo_buscar")
        self.btn_limpiar = QtWidgets.QPushButton(form_entrada)
        self.btn_limpiar.setGeometry(QtCore.QRect(750, 60, 89, 25))
        self.btn_limpiar.setObjectName("btn_limpiar")
        self.line_2 = QtWidgets.QFrame(form_entrada)
        self.line_2.setGeometry(QtCore.QRect(20, 210, 821, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tw_productos = QtWidgets.QTableWidget(form_entrada)
        self.tw_productos.setGeometry(QtCore.QRect(20, 240, 821, 192))
        self.tw_productos.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.tw_productos.setAutoScrollMargin(16)
        self.tw_productos.setObjectName("tw_productos")
        self.tw_productos.setColumnCount(4)
        self.tw_productos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_productos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_productos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_productos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_productos.setHorizontalHeaderItem(3, item)
        self.tw_productos.horizontalHeader().setDefaultSectionSize(195)
        self.btn_confirmar = QtWidgets.QPushButton(form_entrada)
        self.btn_confirmar.setGeometry(QtCore.QRect(750, 440, 89, 25))
        self.btn_confirmar.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_confirmar.setObjectName("btn_confirmar")
        self.layoutWidget = QtWidgets.QWidget(form_entrada)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 170, 163, 28))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.doubleSpinBox.setMaximum(9999.99)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.layoutWidget1 = QtWidgets.QWidget(form_entrada)
        self.layoutWidget1.setGeometry(QtCore.QRect(290, 170, 153, 28))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget1)
        self.dateEdit.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.layoutWidget2 = QtWidgets.QWidget(form_entrada)
        self.layoutWidget2.setGeometry(QtCore.QRect(130, 130, 291, 27))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cbx_producto = QtWidgets.QComboBox(self.layoutWidget2)
        self.cbx_producto.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.cbx_producto.setObjectName("cbx_producto")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbx_producto)

        self.retranslateUi(form_entrada)
        QtCore.QMetaObject.connectSlotsByName(form_entrada)

    def retranslateUi(self, form_entrada):
        _translate = QtCore.QCoreApplication.translate
        form_entrada.setWindowTitle(_translate("form_entrada", "Formulario de Entrada"))
        self.btn_buscar.setText(_translate("form_entrada", "Buscar"))
        self.btn_agregar.setText(_translate("form_entrada", "Agregar"))
        self.label.setText(_translate("form_entrada", "Producto Nombre :"))
        self.label_2.setText(_translate("form_entrada", "Producto Codigo :"))
        self.btn_limpiar.setText(_translate("form_entrada", "Limpiar"))
        item = self.tw_productos.horizontalHeaderItem(0)
        item.setText(_translate("form_entrada", "id"))
        item = self.tw_productos.horizontalHeaderItem(1)
        item.setText(_translate("form_entrada", "Producto"))
        item = self.tw_productos.horizontalHeaderItem(2)
        item.setText(_translate("form_entrada", "Cantidad"))
        item = self.tw_productos.horizontalHeaderItem(3)
        item.setText(_translate("form_entrada", "fecha"))
        self.btn_confirmar.setText(_translate("form_entrada", "Confirmar"))
        self.label_5.setText(_translate("form_entrada", "Cantidad :"))
        self.label_6.setText(_translate("form_entrada", "Fecha  :"))
        self.label_3.setText(_translate("form_entrada", "Producto :"))

