# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_lista_producto.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_lista_producto(object):
    def setupUi(self, form_lista_producto):
        form_lista_producto.setObjectName("form_lista_producto")
        form_lista_producto.resize(712, 551)
        form_lista_producto.setStyleSheet("background-color: rgb(140, 198, 63);")
        self.lne_nombre_buscar = QtWidgets.QLineEdit(form_lista_producto)
        self.lne_nombre_buscar.setGeometry(QtCore.QRect(170, 20, 231, 25))
        self.lne_nombre_buscar.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lne_nombre_buscar.setObjectName("lne_nombre_buscar")
        self.btn_limpiar = QtWidgets.QPushButton(form_lista_producto)
        self.btn_limpiar.setGeometry(QtCore.QRect(570, 50, 89, 25))
        self.btn_limpiar.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_limpiar.setObjectName("btn_limpiar")
        self.lne_codigo_buscar = QtWidgets.QLineEdit(form_lista_producto)
        self.lne_codigo_buscar.setGeometry(QtCore.QRect(170, 50, 231, 25))
        self.lne_codigo_buscar.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lne_codigo_buscar.setObjectName("lne_codigo_buscar")
        self.label = QtWidgets.QLabel(form_lista_producto)
        self.label.setGeometry(QtCore.QRect(20, 20, 141, 17))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(form_lista_producto)
        self.line.setGeometry(QtCore.QRect(20, 110, 651, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(form_lista_producto)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 141, 17))
        self.label_2.setObjectName("label_2")
        self.btn_buscar = QtWidgets.QPushButton(form_lista_producto)
        self.btn_buscar.setGeometry(QtCore.QRect(480, 20, 89, 25))
        self.btn_buscar.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_buscar.setObjectName("btn_buscar")
        self.tw_producto = QtWidgets.QTableWidget(form_lista_producto)
        self.tw_producto.setGeometry(QtCore.QRect(20, 140, 661, 381))
        self.tw_producto.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.tw_producto.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_producto.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_producto.setObjectName("tw_producto")
        self.tw_producto.setColumnCount(6)
        self.tw_producto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_producto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_producto.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_producto.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_producto.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_producto.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_producto.setHorizontalHeaderItem(5, item)
        self.btn_nuevo = QtWidgets.QPushButton(form_lista_producto)
        self.btn_nuevo.setGeometry(QtCore.QRect(570, 20, 89, 25))
        self.btn_nuevo.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_nuevo.setObjectName("btn_nuevo")
        self.btn_actualizar = QtWidgets.QPushButton(form_lista_producto)
        self.btn_actualizar.setGeometry(QtCore.QRect(480, 50, 89, 25))
        self.btn_actualizar.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_actualizar.setObjectName("btn_actualizar")

        self.retranslateUi(form_lista_producto)
        QtCore.QMetaObject.connectSlotsByName(form_lista_producto)

    def retranslateUi(self, form_lista_producto):
        _translate = QtCore.QCoreApplication.translate
        form_lista_producto.setWindowTitle(_translate("form_lista_producto", "Lista de productos"))
        self.btn_limpiar.setText(_translate("form_lista_producto", "Limpiar"))
        self.label.setText(_translate("form_lista_producto", "Producto Nombre :"))
        self.label_2.setText(_translate("form_lista_producto", "Producto Codigo :"))
        self.btn_buscar.setText(_translate("form_lista_producto", "Buscar"))
        item = self.tw_producto.horizontalHeaderItem(0)
        item.setText(_translate("form_lista_producto", "ID"))
        item = self.tw_producto.horizontalHeaderItem(1)
        item.setText(_translate("form_lista_producto", "Codigo"))
        item = self.tw_producto.horizontalHeaderItem(2)
        item.setText(_translate("form_lista_producto", "Nombre"))
        item = self.tw_producto.horizontalHeaderItem(3)
        item.setText(_translate("form_lista_producto", "Descripcion"))
        item = self.tw_producto.horizontalHeaderItem(4)
        item.setText(_translate("form_lista_producto", "Stock"))
        item = self.tw_producto.horizontalHeaderItem(5)
        item.setText(_translate("form_lista_producto", "Cod producto"))
        self.btn_nuevo.setText(_translate("form_lista_producto", "Nuevo"))
        self.btn_actualizar.setText(_translate("form_lista_producto", "Actualizar"))

